### PR TITLE
Add missing tiles and biomes + Polish translation

### LINKED ISSUE #1: Missing Biome: Mangrove Swamp
Tiles, texture sets, and textures need to be added for mangrove swamps (1.19+)

This is currently covered by the regular swamp texture thanks to the swamp tag.

### LINKED ISSUE #2: Missing Biome: Cherry Grove
Tiles, texture sets, and textures need to be added for cherry groves (1.20+)

This is currently covered by the regular mountain texture, which isn't as clear.

### LINKED ISSUE #5: Missing Structure: Igloo

### LINKED ISSUE #6: Missing Structure: Swamp Hut

### LINKED ISSUE #7: Missing Structure: Desert Pyramid

### LINKED ISSUE #16: Missing Structure: Jungle Pyramid

### PR DESCRIPTION
**Pull request by lumiscosity**
Closes #16, closes #7, closes #6, closes #5, closes #2 and closes #1.
Sprites are provided for #20 and #3, but with no code implementation (pillager outposts are made from parts and shipwrecks require beached code checks) - some help would be appreciated!
Also implements a brush marker (as mentioned in #4), custom sprites for the Bamboo Jungle and a Polish translation.

The structures might need testing for possible tile connections for the JSON and for if they work in the first place; I wasn't able to get a running build up since it requires a build of Surveyor and it's getting pretty late for me. I did extensively test the biomes though!

I marked the PR as a draft, as all features added are up for discussion and potential fixing.

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
No way! Thanks so much for stepping up for tile art - it really helps us out ^^

We'll see if we can't retarget this for 1.x and then merge it into 2.x following (or cherry pick it into 1.x after merging) - just so it's out there for people with existing saves.

We also noticed recently that there's still a lot of files set up for hills biomes (which don't exist anymore) but that the main biome file doesn't have elevation-specific tiling. We've been planning to fix it up by deleting the hills biome files and adding their tiles as high elevation in the main biome - so we'll try cover both in the same update.

Thanks again!

**Comment by sleepingdragoninn** [comment]
Here's the test results after patching up the missing bits!

Desert Temple:
java_0YOuivOygf

Jungle Temple + Bamboo Jungle:
java_wqhkQ1rcRe<br/>
So unfortunately you can see there's some stitching issues here. These are resolved if i remove the random jungle textures:
image<br/>
But it doesn't look quite as good. This is something we're planning to fix in the future by having individual textures define their own stitching logic, instead of the overall textureset. This is good enough as is though!


Swamp Hut:
java_U8EFY5Ptua

Igloo:
java_qAycHy1TTQ

Cherry Grove:
java_WxzkiqgsNR

Mangrove Swamp:
java_9HF43SZW72

Beached Shipwreck: 
image<br/>
We just used an aboveground check for this one for now - we'll need to look into whether we can support custom piece data in surveyor later, or whether we should do something fancier (like combining it with terrain data)

Pillager outposts + camps:
image

Brush Marker:
image<br/>
I like this one, but i'm not going to rig it up to trail ruins just yet, because it might make them too loud and obvious - i'll see!

**Review by sleepingdragoninn — APPROVED** [review]

**Comment by sleepingdragoninn** [comment]
@lumiscosity if you're happy with everything above just undraft the PR and I'll merge it in ^^

**Comment by sleepingdragoninn** [comment]
Oh last question - the art in this repo is currently CC-BY-NC-SA toward Hunternif, the original dev and artist - for the textures that aren't derivative of those, i can explicitly specify whichever license you'd prefer (preferably a CC license) for these assets - just let me know if any textures are derivative, and which CC you'd prefer!

**Comment by sleepingdragoninn** [comment]
(oops, pushed a readme change to this branch instead of main - ignore that!)

**Comment by lumiscosity** [comment]
the brush texture is a recolour of the vanilla brush texture; the rest of the textures are drawn by me and CC-BY-NC-SA just like the original.
i agree with not having the brush marker appear on trail ruins - they are meant to be more secretive structures, after all.
the swamp hut is meant to connect to swamp tiles - other than that, everything looks good!

**Comment by sleepingdragoninn** [comment]
image

fixed up the swamp hut stitching, thanks for pointing that out!

**Comment by sleepingdragoninn** [comment]
released as 1.2.0 now! fixed up a few extra things like igloos not appearing because the above ground check was too picky, and the 1.x versions not having list/feature jigsaw support for the pillager outpost.

**Pull request merged**
