### PR TITLE
Add new village textures

### LINKED ISSUE #47: Vanilla Structure: Taiga Village Small House
closest relative: [small_house.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/plains/small_house.png)
image

### LINKED ISSUE #48: Vanilla Structure: Snowy Village Small House
closest relative: [small_house.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/plains/small_house.png)

armorer

butchers

fletcher

masons

small house

small house

small house

### LINKED ISSUE #49: Vanilla Structure: Village Market Stalls (meeting point)
closest relative: [meeting_point.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/plains/meeting_point.png)

desert

plains

plains

plains

savanna

### LINKED ISSUE #110: Vanilla Structure: Snowy Village Small Igloo
closest relatives: [small_house.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/savanna/small_house.png) [igloo.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/igloo/igloo.png)

medium house

medium house

small house

small house

small house

small house

### LINKED ISSUE #111: Vanilla Structure: Desert Village Path
closest relative: [path_crossroads.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/path_crossroad.png)

image

Desert path is much more subtle - made of sandstone among sand. Intersections have a distinct cornered look. lamps along path are very frequent (a variant path_crossroad_lamp.png texture could be made and mixed in randomly)

### LINKED ISSUE #112: Vanilla Structure: Savanna/Taiga Village Rough Farm
closest relative: [small_farm.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/plains/small_farm.png)

preview

preview

preview

preview

### LINKED ISSUE #113: Vanilla Structure: Village Double Arch Wood House
closest relative: [small_house.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/plains/small_house.png)

plains medium house

plains tannery

snowy cartographers

taiga medium house

### LINKED ISSUE #114: Vanilla Structure: Village Two-Storey House
closest relative: [small_house.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/plains/small_house.png)

plains big house

plains butcher

plains library

plains library

plains small house

snowy medium house

taiga cartographer house

taiga library

taiga medium house

taiga medium house

### LINKED ISSUE #115: Vanilla Structure: Savanna Village Double House
closest relative: [small_house.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/savanna/small_house.png)

savanna medium house

savanna medium house 2

### LINKED ISSUE #116: Vanilla Structure: Savanna Village Shallow Roof House
closest relative: [small_house.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/savanna/small_house.png) (savanna)

armorer

cartographer

fletcher

library

mason

small house

tannery

weaponsmith

### LINKED ISSUE #117: Vanilla Structure: Village Covered Well Meeting Point
closest relative: [meeting_point.png](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/resources/assets/antique_atlas/textures/atlas/tile/structure/village/plains/meeting_point.png)

desert

plains

savanna

snowy

taiga

### PR DESCRIPTION
**Pull request by lumiscosity**
See title.

Closes #47
Closes #48
Closes #49
Closes #110
Closes #111
Closes #112
Closes #113
Closes #114
Closes #115
Closes #116
Closes #117

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
Thanks! I'll take it from here

**Comment by sleepingdragoninn** [comment]
java_fRNVgNHPvR

**Comment by lumiscosity** [comment]
oh, i totally made the borders on the well too bright. give me a sec

**Comment by sleepingdragoninn** [comment]
image

image

image

desert done - thanks for the help with the covered well!

**Comment by sleepingdragoninn** [comment]
image

image

image

**Comment by sleepingdragoninn** [comment]
unidirectional paths exposing themselves a little, might wanna change some buildings to vertical or horizontal path connections only later.

image

image

image

image

**Comment by sleepingdragoninn** [comment]
taiga now

image

image

**Comment by sleepingdragoninn** [comment]
snowy - snowed-in smaller house is mildly believable, but the larger one i've definitely screwed up - i'll have to try the snow edit again

image

image

**Comment by sleepingdragoninn** [comment]
better.

image

**Comment by sleepingdragoninn** [comment]
think i'm done - general previews

image
image
image
image
image
image
image
image

**Comment by sleepingdragoninn** [comment]
@lumiscosity let me know if you're happy how this is all showing up in-game ^^ I'll put it out as 2.9

**Comment by lumiscosity** [comment]
these look excellent, good job on the additional edits!

**Comment by lumiscosity** [comment]
hi! just letting you know the art credit file hasn't been updated with the new textures

**Comment by sleepingdragoninn** [comment]
good point! i'll sweep through it today and figure out some way to effectively categorize my composites

**Comment by sleepingdragoninn** [comment]
done! redid the format so it's easier to update in future as well.

**Pull request merged**
