### PR TITLE
Port to 1.21

### PR DESCRIPTION
**Pull request by macbrayne**
Notes:
- I had to remove super.render() from Component.render(). Doing so required rendering the MarkerModal Drawables explicitly.

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
fixed up where i can - can you give this another test and mark it ready when you're ready?

**Comment by macbrayne** [comment]
I visited the biomes a to p and everything looks fantastic. Nether fortresses look amazing. Ocean monuments and woodland mansions icons work. Nether portal icon works. Player death works (odd death names lol).
End cities don't get displayed which I assume is intended?

**Comment by sleepingdragoninn** [comment]
end cities should appear, i'll check on my side.

**Review by sleepingdragoninn — APPROVED** [review]
from inspection, it seems like structure discovery is broken for end cities - existing discovered end cities from a 1.20 save work, so that's a surveyor bug.

**Pull request merged**
